name: Add issues and prs to a project - team

on:
  issues:
    types:
      - opened
      - reopened

  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add issue and prs to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/pyladies-colombia/projects/1
          github-token: ${{ secrets.ERTYUI }}
          labeled:
          label-operator: